export const artworks = [
  {
    title: "Peace",
    media: "Insulation board, paint, mirrors, sand",
    ks: "Key Stage 4",
    description: "A sculptural installation addressing conflict in Israel and Palestine, inspired by the work of Robert Smithson and Mike Nelson, as well as Middle Eastern religious architecture. This was a final GCSE coursework piece completed for the mock exam in response to the theme 'Fragments'",
    image_url: "/chesky-peace.jpg",
    id:"001",
  },
    {
    title: "Circles",
    media: "Acrylic on canvas",
    ks: "Key Stage 4",
    description: "A large painting consisting of a series of circular objects found within school. This work is inspired by Damian Hirst's dot paintings and the colourful work of Michael Craig-Martin. It was created as a final exam piece in response to the theme 'Lock'",
    image_url: "/moishe-lock.jpg",
    id:"002",
  },
    {
    title: "Start/End",
    media: "Digital illustion",
    ks: "Key Stage 4",
    description: "Inspired by Sean C Jackson, this illustration explores the theme 'Lock' and was created as a final GCSE exam piece. It was developed through hand drawn studies into a digital illustration using Adobe Illustrator.",
    image_url: "/elimelech-maze.jpg",
    id:"003",
  },
  {
    title: "Surface",
    media: "Casting, paint, wood",
    ks: "Key Stage 4",
    description: "This 3D wall hanging was inspired by the work of the Boyle Family, and further developed through study of the Painting with White room at Tate Modern. Created using the casting process it was produced as a final GCSE coursework piece using the theme 'Fragments'",
    image_url: "/yitzy-surface.jpg",
    id:"004",
  },
  {
    title: "Shells",
    media: "Screenprint and Linoprint",
    ks: "Key Stage 3",
    description: "Part of a year 9 printing project in which students learn a range of printing techniques including screen print and lino print. These shell prints were created in response to the work of Henri Matisse and M.C. Escher",
    image_url: "/shells.jpg",
    id:"005",
  },
  {
    title: "Natural forms inspired pots",
    media: "ceramics",
    ks: "Key Stage 3",
    description: "Inspired by drawings of fruit, these pots were created by year 9 students in response to the work of ceramicist Kate Malone. During the project students learnt a range of techniques including coil, slab and joining.",
    image_url: "/ceramics.jpg",
    id:"007",
  },
    {
    title: "Still life with bottle",
    media: "Watercolour on paper",
    ks: "Key Stage 3",
    description: "These paintings are inspired by Cubist still life artworks by Juan Gris and Pablo Picasso, and explore how objects can be shown from multiple viewpoints in a single artwork.",
    image_url: "cubism.jpg",
    id:"006",
  },
]
