export const artworks = [
  {
    title: "Peace",
    media: "Insulation board, paint, mirrors, sand",
    ks: "Key Stage 4",
    description: "A sculptural installation addressing conflict in Israel and Palestine, inspired by the work of Robert Smithson and Mike Nelson, as well as Middle Eastern religious architecture.",
    image_url: "/chesky-peace.jpg",
    id:"001",
  },
    {
    title: "Lock",
    media: "Acrylic on canvas",
    ks: "Key Stage 4",
    description: "A painting of a series of circular objects inspired by Damian Hirst's dot paintings and the colourful work of Michael Craig-Martin.",
    image_url: "/moishe-lock.jpg",
    id:"002",
  },
    {
    title: "Maze",
    media: "Digital illustion",
    ks: "Key Stage 4",
    description: "Inspired by Sean C Jackson, this illustration was developed through hand drawn studies into a digital illustration using Adobe Illustrator.",
    image_url: "/elimelech-maze.jpg",
    id:"003",
  },
  {
    title: "Surface",
    media: "Casting, paint",
    ks: "Key Stage 4",
    description: "A 3D wall hanging inspired by the Painting with White room at Tate Modern and the work of the Boyle Family",
    image_url: "/yitzy-surface.jpg",
    id:"004",
  },
  {
    title: "Shells",
    media: "Screenprint and Linoprint",
    ks: "Key Stage 3",
    description: "A range of shell prints created in response to the work of Henri Matisse and M.C. Escher",
    image_url: "/shells.jpg",
    id:"005",
  },
  {
    title: "Natural forms inspired pots",
    media: "ceramics",
    ks: "Key Stage 3",
    description: "Pots inspired by fruit created in response to the work of ceramicist Kate Malone. Created using the coil technique",
    image_url: "/ceramics.jpg",
    id:"007",
  },
    {
    title: "Still life with bottle",
    media: "Watercolour on paper",
    ks: "Key Stage 3",
    description: "Paintings inspired by Cubist artworks by Juan Gris and Pablo Picasso, exploring how objects can be shown from multiple viewpoints in a single artwok.",
    image_url: "cubism.jpg",
    id:"006",
  },
]
